ProjEcom/ProjEcom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url

from ecomapps import views


urlpatterns = [
    url(r'^$', views.index, name="index"), # accueil
    url(r'^ecomapps/', include('ecomapps.urls')),
    #url(r'^admin/', admin.site.urls),
    url(r'^content/', admin.site.urls),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ProjEcom/ecomapps/urls.py
from django.conf.urls import url

from . import views # import view.py in urls.py

app_name = 'ecomapps'

urlpatterns = [
    url(r'^$', views.listing, name="listing"), #"ecomapps/void
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name="detail"),
    url(r'^search/$', views.search, name="search")
]

ProjEcom/ecomapps/models.py
from django.db import models

# Create your models here.
class Artist(models.Model):
    name = models.CharField('Nom', max_length=200, unique=True)

    def __str__(self):
        return self.name

class Contact(models.Model):
    email = models.EmailField(max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Album(models.Model):
    reference = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True)
    title = models.CharField(max_length=200)
    picture = models.URLField()
    artist = models.ManyToManyField(Artist, related_name='albums', blank=True)

    def __str__(self):
        return self.title

class Booking(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    contacted = models.BooleanField(default=False)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    album = models.OneToOneField(Album, on_delete=models.CASCADE)

    def __str__(self):
        return self.contact.name

ProjEcom/ecomapps/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Album, Artist, Contact, Booking
#from django.template import loader
from .form import ContactForm, ParagraphErrorList
# Create your views here.


def index(request):
    albums = Album.objects.filter(available=True).order_by('-created_at')[:23]
    # formated_albums = ["<li>{}</li>".format(album.title) for album in albums]
    # message = """<ul>{}</ul>""".format("\n".join(formated_albums))
    # return HttpResponse(message)
    formated_albums = [f"<li>{album.title}</li>" for album in albums]
    #message = f"""<ul>{"".join(formated_albums)}</ul>"""
    template = loader.get_template('ecomapps\index.html')
    #return HttpResponse(message)
    context = {'albums': albums}
    #return HttpResponse(template.render(context, request=request))
    return render(request, 'ecomapps\index.html', context)

def listing(request):
    albums = Album.objects.filter(available=True)
    #formated_albums = ["<li>{}</li>".format(album.title) for album in albums]
    #message = """<ul>{}</ul>""".format("\n".join(formated_albums))
    #return HttpResponse(message)
    context = {'albums': albums}
    #return HttpResponse(template.render(context, request=request))
    return render(request, 'ecomapps\listing.html', context)


def detail(request, album_id):
    #album = Album.objects.get(pk=album_id)
    album = get_object_or_404(Album, pk=album_id)
    artists_name = " ".join([artist.name for artist in album.artist.all()])
    # message = f"Le nom de l'album est {album.title}. Il a été écrit par {artists} "
    # return HttpResponse(message)
    context = {
        'album_title': album.title,
        'album_name': artists_name,
        'album_id': album.id,
        'thumbnail': album.picture
               }
    if request.method == 'POST':
        form = ContactForm(request.POST, error_class=ParagraphErrorList)
        if form.is_valid():
            #email = request.POST.get('email')
            #name = request.POST.get('name')
            email = form.cleaned_data['email']
            name = form.cleaned_data['name']

            contact = Contact.objects.filter(email=email)
            if not contact.exists():
                # If a contact is not registered, create a new one.
                contact = Contact.objects.create(
                    email=email,
                    name=name
                )
            else:
                contact = contact.first()

            album = get_object_or_404(Album, id=album_id)
            booking = Booking.objects.create(
                contact=contact,
                album=album
            )
            album.available = False
            album.save()
            context = {
                'album_title': album.title
            }
            return render(request, 'ecomapps/merci.html', context)
        else:
            context['errors'] = form.errors.items()
    else:
        form = ContactForm()

    context['form'] = form

    # context = {
    #     'album_title': album.title,
    #     'album_name': artists_name,
    #     'album_id': album.id,
    #     'thumbnail': album.picture,
    #     'form':form
    #            }
    #return HttpResponse(template.render(context, request=request))
    return render(request, 'ecomapps\detail.html', context)


def search(request):
    # obj = str(request.GET)
    # query = request.GET['query']
    # message = f"propriété GET : {obj} et requête : {query}"
    # #http: // 127.0.0.1: 8000 / ecomapps / search /?query = Celine
    # return HttpResponse(message)

    query = request.GET.get('query')
    if not query:
        albums = Album.objects.all()
    else:
        # title contains the query is and query is not sensitive to case.
        albums = Album.objects.filter(title__icontains=query) #pas de correspondance exacte

        if not albums.exists(): # items exist True or false
            albums = Album.objects.filter(artist__name__icontains=query) #search with name artist

        # if not albums.exists(): # items exist True or false
        #     message = "Misere de Misere, nous n'avons trouver aucun resultat"
        #
        # else:
        #     albums = [f"<li>{album}</li>" for album in albums]
        #     message = f""" Nous avons trouver les correspondances, a votre requete ! les voici :<ul>{"<li></li>".join(albums)}</ul>"""

    title = "Resultats pour la requête %s"%query
    context = {
        'albums': albums,
        'title': title
    }

    #return HttpResponse(message)
    return render(request, 'ecomapps\search.html', context)

ProjEcom/ecomapps/templates/ecomapps/base.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'ecomapps/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'ecomapps/css/business-casual.css' %}" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="brand"><a href="/">Le bateau pirate</a></div>
    <div class="address-bar">Radio rock, Mer du nord (ou dans le 20e, à Paris)</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Le bateau pirate</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'ecomapps:listing' %} ">Tous nos disques</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <div class="container">
      <div class="row">
        <div class="box">
            {% block content %}
            {% endblock %}
        </div>
      </div>
    </div>


    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; <a href="http://github.com/bkablam11" target="_blank">Blanchard Kablam</a> de <a href="#" target="_blank">Simplon.ci</a></p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'ecomapps/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'ecomapps/js/bootstrap.min.js' %}"></script>

  </body>
</html>

ProjEcom/ecomapps/templates/ecomapps/detail.html
{% extends 'ecomapps/base.html' %}

{% block content %}
<hr>
<h1 class="intro-text text-center">{{ album_title }}</h1>
<hr class="detail-separator">
<div class="col-md-6">
  <img src="{{ thumbnail }}" alt="{{ album_title }}" class="img-responsive">
</div>
<div class="col-md-6">
  <div style="margin-bottom:45px">
    <h2 class="text-center artist_name">Artistes</h2>
    <p>{{ artists_name }}</p>
  </div>

  <h2 class="text-center artist_name">Réserver {{ album_title }}</h2>
  <p style="margin-bottom: 20px;">Demandez-nous de mettre de côté {{ album_title }} et venez le chercher dès demain en magasin ! </p>
  <form class="form-inline" action="{% url 'ecomapps:detail' album_id=album_id %}" method="post">
    {% csrf_token %}
    <div class="form-group {% if form.name.errors %}has-warning has-feedback{% endif %}">
      <label for="{{ form.name.id_for_label }}" class="control-label">Nom</label>
      <!-- <input type="text" name="name" value="" id="name"> -->
      {{ form.name }}
    </div>
    <div class="form-group {% if form.email.errors %}has-warning has-feedback{% endif %}">
      <label for="{{ form.email.id_for_label }}" class="control-label">E-mail</label>
      <!-- <input type="text" name="email" value="" id="email"> -->
      {{ form.email }}
    </div>
    <!-- <input type="hidden" class="hidden" value="{{ album.id }}" name="album_id"> -->

    <button type="submit" class="btn btn-success">Réserver</button>
  </form>

    {% if errors %}
    <div>
      {% for key, error in errors %}
      {% autoescape off %}
        {{ error }}
      {% endautoescape %}
      {% endfor %}
    </div>
    {% endif %}

</div>


{% endblock %}

ProjEcom/ecomapps/templates/ecomapps/index.html
{% extends 'ecomapps/base.html' %}

{% block content %}

    {% include 'ecomapps\list.html' with list_title='Nos derniers disques' %}

{% endblock %}

ProjEcom/ecomapps/templates/ecomapps/list.html
<div class="col-lg-12">
    <hr>
    <h2 class="intro-text text-center">{{ list_title }}
    </h2>
    <hr class="detail-separator">
</div>

{% include 'ecomapps/search_form.html' %}

{% if albums|length_is:"0"%}
<div class="text-center">
    Palsambleu ! Nous n'avons trouvé aucun resultat.
</div>
{% else %}
    {% for album in albums %}
    <div class="col-sm-4 text-center">
            <a href="{% url 'ecomapps:detail' album_id=album.id%} ">
              <img class="img-responsive" src="{{ album.picture }}" alt="{{ album.title }}">
            </a>
        <h3><a href="{% url 'ecomapps:detail' album_id=album.id%}">{{ album.title }}</a></h3>
            {% for artist in album.artists.all %}
                <p>{{ artist.name }}</p>
            {% endfor %}
    </div>
    <!--<li>{{ album.title }}</li>-->
    {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
    {% endfor %}
{% endif %}

ProjEcom/ecomapps/templates/ecomapps/listing.html
{% extends 'ecomapps/base.html' %}

{% block content %}

    {% include 'ecomapps/list.html' with list_title='Tous nos disques' %}

{% endblock %}

ProjEcom/ecomapps/templates/ecomapps/merci.html
{% extends 'ecomapps/base.html' %}

{% block content %}

    <hr>
    <h1 class="intro-text text-center">Merci !</h1>
    <hr class="detail-separator">
    <p>L'album <em>{{ album_title }}</em> vient d'être retiré des rayonnages. Une main délicate a déposé votre nom sur sa couverture et l'a rangé en vous attendant. Dépêchez-vous ! <em>{{ album_title }}</em> trépigne d'impatience et chante déjà vos louanges.</p>
    <hr>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ZSbuikMdgqA" frameborder="0" allowfullscreen></iframe>
    </div>

{% endblock %}

ProjEcom/ecomapps/templates/ecomapps/search.html
{% extends 'ecomapps/base.html' %}

{% block content %}

    {% include 'ecomapps/list.html' with list_title=title %}

{% endblock %}

ProjEcom/ecomapps/templates/ecomapps/search_form.html
<div class="container">
  <div class="col-lg-12 detail-separator">
    <form class="col-md-6 col-md-offset-3 text-center" action="{% url 'ecomapps:search' %}" method="get" accept-charset="utf-8">
      <div class="form-group">
        <label for="searchForm">Chercher un disque</label>
        <input id="searchForm" class="form-control" name="query">
      </div>
      <span class="help-block" id="helpBlock">Trouvez le CD de vos rêves en tapant son titre ou le nom d'un des artistes.</span>
    </form>
  </div>
</div>